### ISSUE TITLE
Specs should pass on JRuby

### ISSUE THREAD

**Issue by thbar** [LTe/iban-check#7]
The command line part doesn't pass on JRuby. I'll have a look at this.

**Comment by LTe** [comment]
Up... fail http://travis-ci.org/#!/LTe/iban-check/jobs/630182

**Comment by thbar** [comment]
I tried to use the command line with JRuby and things work as expected.

I believe this may be an issue at Aruba API + JRuby (I will have a closer look).

**Comment by LTe** [comment]
```
$ rvm jruby-head
$ rake
Finished in 36.97 seconds
16 examples, 0 failures
```

**Comment by thbar** [comment]
woot!

-- Thibaut

Le 8 févr. 2012 à 17:39, "Piotr Niełacny"
reply@reply.github.com
a écrit :

**Comment by LTe** [comment]
On jruby-1.6.5 tests do not pass.

jruby-head

```
jruby 1.7.0.dev (ruby-1.8.7-p357) (2012-01-25 dad8fcc) (Java HotSpot(TM) Server VM 1.6.0_26) [linux-i386-java]
```

**Comment by LTe** [comment]
If somebody want to use jruby, they must use 1.7.x

**Comment by thbar** [comment]
Do you mean the gem will not work on jruby 1.6? Or just the specs?

**Comment by LTe** [comment]
Gem works for me on 1.6.x. Unfortunately, tests do not pass but only those associated with the command line.

**Comment by thbar** [comment]
Cool thanks! Good to know.

FWIW here it's in production on MRI 1.8.7 on Windows :)

-- Thibaut

Le 14 févr. 2012 à 20:01, "Piotr Niełacny"
reply@reply.github.com
a écrit :
